- supabase/seed.sql
User story 124
I added datas to seed.sql for product.
[X] ✨ New feature
[ ] 🐛 Bug fix
[ ] 🧹 Code cleanup/refactor
[ ] 📝 Documentation update
[ ] 🔧 Build/CI pipeline update
[ ] ⚠️ Breaking change
> feat: add product data for database seeding

- app/api/suppliers/route.ts
- lib/api-response.ts
- types/api-response-type.ts
ID-123-Supplier Management
1. I added get all suppliers API with pagination supported (/api/suppliers)
2. I added API Response utility function
[x] ✨ New feature
[ ] 🐛 Bug fix
[ ] 🧹 Code cleanup/refactor
[ ] 📝 Documentation update
[ ] 🔧 Build/CI pipeline update
[ ] ⚠️ Breaking change
> feat: get all suppliers & api response utility

- app/api/suppliers/[id]/route.ts
- app/api/suppliers/route.ts
- types/supplier/supplier.type.ts
ID-123-Supplier Management
`GET /api/suppliers?page=1&pageSize=5&status=true&sort=name_asc` - Get all suppliers with filter by status and sort by name
`GET /api/suppliers/:id` – Get supplier by id 
`POST /api/suppliers` – Create a new supplier
`PUT /api/suppliers/:id` – Edit supplier by id
`DELETE /api/suppliers/:id` - Delete supplier by id
> feat: Supplier CRUD APIs

- app/(portal)/(nexus)/products/page.tsx
Backlog ID - 124
I added statistics card.
[x] ✨ New feature
[ ] 🐛 Bug fix
[ ] 🧹 Code cleanup/refactor
[ ] 📝 Documentation update
[ ] 🔧 Build/CI pipeline update
[ ] ⚠️ Breaking change
> feat: add statistics card to product page

- app/(portal)/(nexus)/suppliers/[id]/page.tsx
- app/(portal)/(nexus)/suppliers/components/DetailsCard.tsx
- app/(portal)/(nexus)/suppliers/components/HistoryCard.tsx
- app/(portal)/(nexus)/suppliers/page.tsx
- components/Breadcrumbs.tsx
ID-123-Supplier Management
I added supplier details view page including History Tab with demo data.
> feat: supplier details page

- app/(portal)/(nexus)/suppliers/page.tsx
- app/api/suppliers/route.ts
- types/supplier/supplier.type.ts
ID-123-Supplier Management
I implemented
1. Sorting by Supplier Name (A-Z/Z-A)
2. Search
3. Statistics Data Count for All, Active, Inactive
> integrate: sorting and search

- components/Modal.tsx
- theme/ant-theme.ts
Don't relate to any backlog
I created a custom modal component
> feat: custom modal component

- app/(portal)/products/[id]/page.tsx
- components/products/ConfirmModal.tsx
- types/category/category.type.ts
- types/product/product.type.ts
Backlog ID 124 - Product catalog management
I created
- deactivate modal
- delete modal
> feat: create deactivate and delete modal

- .github/pull_request_template.md
No related backlog id exists
added pr template
> feat: pr template for easy use

- app/(portal)/(procurement)/products/[id]/page.tsx
- app/(portal)/(procurement)/products/page.tsx
- components/products/CreateCategoryModal.tsx
- components/products/CurrentStockCard.tsx
- components/products/PriceHistoryCard.tsx
- components/products/ProductFormModal.tsx
Backlog ID 124-Product Catalog Management
I refactored
- current stock card
- price history card
> ID-124-Product Catalog Management

- app/(portal)/(finance)/budgets/page.tsx
- components/budgets/BudgetStatsCard.tsx
Backlog ID - 114-Create Budgets
I create
- Budget stats card UI
- Header section
> feat: budgets page and budget stats card

- schemas/budgets/budgets.schema.ts
- types/budgets/budgets.type.ts
Backlog ID 114 - Create Budgets
I created
- schemas for zod validation
- types for type safing
> feat: budgets schemas and types

- app/api/purchase-orders/purchase-orders-regions/route.ts
- types/purchase-order/purchase-order-region.type.ts
ID-107 Multi-step-PO-Creation
I added two new APIs for PO Region.
`GET - api/purchase-orders/purchase-orders-regions` - Get all regions
`POST - api/purchase-orders/purchase-orders-regions` - Create new region
> feat: create and get all api for regions

- app/(portal)/(finance)/budgets/page.tsx
Backlog ID 114 - Create budgets
refactored budget page
> chore: remove empty state when data length is 0

- app/(auth)/login/page.tsx
- app/api/auth/check-user/route.ts
Error handling for offline login
> Update: error handling for offline login

- app/api/budgets/route.ts
- components/budgets/steps/StepBudgetDetails.tsx
- components/budgets/steps/StepFinancialParameters.tsx
ID 114 - Create Budgets
I modify
- start date and end date
- created by in post api
> chore: disable startDate before endDate & add created by in post api

- app/api/purchase-orders/[id]/route.ts
- app/api/purchase-orders/drafts/[id]/route.ts
- app/api/purchase-orders/drafts/route.ts
- types/purchase-order/purchase-order-item.type.ts
- types/purchase-order/purchase-order.type.ts
ID-109-View & Manage Purchase Order Details
I created Purchase Order Details with relation to other tables API `(api/purchase-orders/:id)`
You can view the API response in the attached document file (https://docs.google.com/document/d/10furKj_BN_GA5E31e2r5Lvfl9rMLHUKe2JDaEZzPdRg/edit?usp=sharing)
> feat: purchase order details api

- app/(portal)/(finance)/budget-allocations/create/page.tsx
- app/(portal)/(finance)/budget-allocations/page.tsx
Backlog 117 - Create Budget Allocations
I created
- Breadcrumbs
- Create budget allocations header
> feat: budget allocation & create budget allocation breadcrumbs

- components/budgets/BudgetCard.tsx
- components/budgets/steps/StepFinancialParameters.tsx
> chore: add padding to the budget card

- app/api/purchase-invoices/route.ts
- types/purchase-invoice/purchase-invoice.type.ts
ID-112-Invoice List View
purchase invoice get all api with all required data.
`GET - /api/purchase-invoices?pageSize=50&page=1&q=INV-2024-007&status=Pending&sort=date_desc&amountSort=amount_asc`
> feat: pi get all api

- app/(portal)/(finance)/budget-allocations/create/page.tsx
- app/api/budget-allocations/route.ts
- components/budget-allocations/BudgetAllocationForm.tsx
- supabase/migrations/20250709094757_add_fk_budget_key_po.sql
- utils/uploadTransferEvidence.ts
Backlog ID 117 - Create Budget Allocation
integrated
- create budget api
> integrate: create budget allocation api

- app/(portal)/(finance)/budget-allocations/create/page.tsx
- app/(portal)/(procurement)/purchase-orders/page.tsx
- app/api/budget-allocations/[id]/route.ts
- app/api/budget-allocations/route.ts
- app/api/products/[id]/get-product-price-history/route.ts
- app/api/purchase-orders/drafts/[id]/route.ts
- app/api/purchase-orders/drafts/route.ts
- app/globals.css
- components/budget-allocations/BudgetAllocationForm.tsx
- hooks/products/useCategories.ts
- hooks/products/useProducts.ts
- types/budget-allocations/budget-allocations.type.ts
Backlog ID 117 - Create Budget Allocations
I integrated with PO.
> feat: linked with po and modify api

- app/(portal)/(finance)/budget-allocations/page.tsx
- app/api/budget-allocations/route.ts
- supabase/migrations/20250708044444_add_create_budget_allocation_table.sql
Backlog ID 118 - View & Manage Budget Allocation
I created and integrated
- Allocations List View
- Integrate with API
> feat: integrate budget allocation list views

- app/api/auth/password-login/route.ts
- app/api/auth/users/route.ts
- lib/supabase/admin.ts
> add: api for user creation

- app/(portal)/(procurement)/invoices/[id]/page.tsx
- app/api/purchase-invoices/[id]/route.ts
- app/api/purchase-invoices/edit-history/[id]/route.ts
- components/purchase-invoices/DetailsCard.tsx
- components/purchase-invoices/DetailsPDF.tsx
- components/purchase-invoices/EditHistory.tsx
- components/purchase-invoices/LinkedPO.tsx
- components/purchase-invoices/VoidModal.tsx
- package.json
- pnpm-lock.yaml
- supabase/migrations/20250718110600_add_fk_to_profile_in_pi_audit.sql
- types/purchase-invoice/purchase-invoice.type.ts
ID-113-View & Manage Invoice Details
Invoice details page ui and api integration
> feature: invoice details page

- app/(portal)/(inventory)/stock-management/page.tsx
- components/inventory/StockIn.tsx
- components/inventory/StockOut.tsx
- components/shared/MainLayout.tsx
Backlog ID 120 - Stock In
- stock in forms UI
> feat: stock in form UI

- app/api/stock-transactions/route.ts
- types/stock/stock.type.ts
ID-122-Inventory View & Stock Movement Tracking
Stock transaction API with full filter support
> feat: stock transaction api with full filter support

- components/inventory/stock-management/Inventory.tsx
- components/inventory/stock-management/Transactions.tsx
- types/stock/stock.type.ts
Backlog ID 122
integrated stock transactions api
> integrate: stock transaction api

- components/inventory/stock-management/Inventory.tsx
- components/inventory/stock-management/StockIn.tsx
- components/inventory/stock-management/StockOut.tsx
- types/inventory/inventory.type.ts
Backlog ID 122
bug fix stock in and out
> fix: stock in out quantity zero

- app/(portal)/(procurement)/suppliers/[id]/page.tsx
- app/api/suppliers/invoice-history/[id]/route.ts
- app/api/suppliers/purchase-order-history/[id]/route.ts
- components/suppliers/DetailsCard.tsx
- components/suppliers/HistoryCard.tsx
- components/suppliers/InvoiceHistoryTable.tsx
- components/suppliers/PurchaseOrderHistoryTable.tsx
- components/suppliers/TableWrapper.tsx
- hooks/react-query/usePaginatedById.ts
- types/purchase-invoice/purchase-invoice.type.ts
- types/supplier/supplier.type.ts
TC-123-005
Implemented the history tab in supplier details page.
> feat: implementing the supplier history tab

- app/api/budget-allocations/route.ts
- app/globals.css
- components/budget-allocations/BudgetAllocationForm.tsx
Backlog ID 118 Budget allocations
total budget allocation
> fix: budget allocation fix

- app/(portal)/(procurement)/products/[id]/page.tsx
- app/api/products/[id]/get-usage-history/route.ts
- app/api/products/[id]/route.ts
- hooks/products/useDeactivateProduct.ts
- types/product/product.type.ts
Backlog ID 124 Product catalog
- deactivate
- delete product
> feat: deactivate and delete product api

- app/(portal)/(procurement)/purchase-orders/page.tsx
- app/api/purchase-orders/route.ts
- components/purchase-orders/PoCardView.tsx
- components/shared/StatisticsCards.tsx
- hooks/react-query/useList.ts
- types/purchase-order/purchase-order.type.ts
> PO List view blockers

- app/api/budgets/route.ts
Backlog ID 115 Budgets
- allocated
- allocated variance
- PO status
> chore: allocated and allocated variance according to PO status

- app/api/purchase-invoices/[id]/route.ts
- app/api/purchase-invoices/get-purchase-invoice-no/route.ts
- app/api/purchase-invoices/route.ts
- app/api/warehouses/[id]/route.ts
- utils/generatePiNumber.ts
TC-119-007
Return the invoice number instead of invoice line item id in the warehouse details api.
> Bug fix/tc 119 007

- app/(portal)/(administration)/users/create/page.tsx
- components/users/UserPermissionsTab.tsx
- types/user/user-detail.type.ts
> fix: role-based UI bugs

- app/api/budgets/route.ts
Backlog ID 118
- invoice linked with PO
> feat: invoice amount linked with PO

- components/purchase-orders/steps/StepItemEntry.tsx
> foc bug fix

- components/purchase-orders/steps/StepDateCurrency.tsx
PO Draft Error
Cannot load PO Draft
> fix: po draft error

- app/(portal)/(procurement)/products/page.tsx
- app/api/products/[id]/get-usage-history/route.ts
- components/inventory/stock-management/Inventory.tsx
- components/inventory/stock-management/StockOut.tsx
- components/inventory/stock-management/Transactions.tsx
- components/products/CurrentStockCard.tsx
- components/products/DetailsCard.tsx
- components/suppliers/InvoiceHistoryTable.tsx
- components/suppliers/PurchaseOrderHistoryTable.tsx
> feat: thousand separator for quantity, and amount

- app/(portal)/(procurement)/products/page.tsx
- app/api/products/[id]/get-usage-history/route.ts
- components/inventory/stock-management/Inventory.tsx
- components/inventory/stock-management/StockOut.tsx
- components/inventory/stock-management/Transactions.tsx
- components/products/CurrentStockCard.tsx
- components/products/DetailsCard.tsx
- components/purchase-orders/steps/StepItemEntry.tsx
- components/suppliers/InvoiceHistoryTable.tsx
- components/suppliers/PurchaseOrderHistoryTable.tsx
> Thousand separator

- components/inventory/stock-management/StockIn.tsx
> fix: on preview url

- components/purchase-orders/steps/StepItemEntry.tsx
> debug: available products

- supabase/migrations/20250901043405_add_stock_transaction_assets.sql
Backlog ID 186 - Record & Display Stock out evidence with approval metadata
- added new table stock transaction assets to supabase
> feat: add stock transaction assets

- app/api/stock-transactions/[id]/route.ts
- app/api/stock-transactions/route.ts
- app/api/uploads/direct/route.ts
- components/inventory/stock-management/Transactions.tsx
- package.json
- pnpm-lock.yaml
- types/stock/stock.type.ts
Backlog ID - 186 Record & Display Stock Out Evidence with approval metadata
- ui integration with stock out transactions
> feat: stock out transactions ui with evidence

- components/inventory/stock-management/StockIn.tsx
Backlog ID - 179 Stock In evidence
- fixed image size
> fix: image size

- app/(portal)/(inventory)/stock-management/page.tsx
- app/api/purchase-invoices/route.ts
Bug Fix
Remove the pagination API call for invoices in stock in invoice selection
> fix: remove pagination for invoices in stock in view

- components/inventory/stock-management/StockIn.tsx
Backlog ID 179 Stock In Photo Evidence
- fixed UI error when upload an image with long filename
> fix: UI error when upload an image with long filename

- app/api/products/route.ts
- components/purchase-orders/steps/StepItemEntry.tsx
- types/product/product.type.ts
ID-184-Product Aliases & Tags
Search by alias on po creation item entry step
> feat: add search by alias

- app/api/purchase-orders/export-csv/route.ts
Backlog ID 178 Export csv for purchase order api
- export csv api for purchase orders
> feat: export csv for purchase orders api

- app/(portal)/(inventory)/stock-management/page.tsx
> fix: warehouse pagination in stock management

- app/(portal)/(inventory)/stock-management/page.tsx
- app/api/stock-in/route.ts
- lib/supabase/admin.ts
Backlog ID 178, 186
- insert evidence in only one item
> fix: insert evidence in stock in

- components/inventory/stock-management/StockOut.tsx
Backlog ID 186
- duplicate stock out evidence photos fix
> fix: duplicate stock out evidence photos

- app/(portal)/(procurement)/purchase-orders/page.tsx
- app/api/purchase-orders/route.ts
- components/purchase-orders/PoTableView.tsx
Backlog ID 108 - Purchase Order List View
- sorting purchase orders by po number
> feat: sorting purchase order with PO number

- app/api/purchase-invoices/route.ts
- app/api/stock-in/route.ts
- app/api/stock-transactions/void-preview/[id]/route.ts
- components/inventory/stock-management/VoidModal.tsx
Backlog ID 178 Export CSV for Purchase Orders
- add invoice amount usd
> New feature to Dev (v1.0.1.3)
